"""add attachment to assignments

Revision ID: 0210f4a52a15
Revises: 
Create Date: 2026-03-08 11:43:35.931513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0210f4a52a15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_name', sa.String(length=255), nullable=True))

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('attachment')

    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.drop_column('original_name')

    # ### end Alembic commands ###
